### ISSUE TITLE
RuntimeException when running this example: NeuralStyleTransfer

### ISSUE THREAD

**Issue by lymanzhang** [cansik/deep-vision-processing#11]
Hi, I encountered RuntimeException when running this example: NeuralStyleTransfer, and the processing console prompt: 

creating network...
loading model...
RuntimeException: OpenCV(4.5.3) D:\a\javacpp-presets\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.5.3\modules\dnn\src\torch\THDiskFile.cpp:286: error: (-2:Unspecified error) read error: read 327960 blocks instead of 424899 in function 'TH::THDiskFile_readFloat'

I aware that there wound be some wrong with the opencv dependency in my system (windows 11) , but how to make it right?  thanks a lot.

**Comment by cansik** [comment]
Which version of deep vision is installed? And are you running the example with the default model `InstanceNormCandy`?

**Comment by lymanzhang** [comment]
the version I installed is Release 0.7.0. 
I just run the examples bunded with the lib, for example, when running FaceAgeGenderWebcam, the console prompts RuntimeException information like this: 

creating network...
loading model...
RuntimeException: OpenCV(4.5.3) D:\a\javacpp-presets\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.5.3\modules\dnn\src\caffe\caffe_io.cpp:1171: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse NetParameter file: D:\p5Sketch\libraries\deepvision\library\networks\gender_net.caffemodel in function 'cv::dnn::ReadNetParamsFromBinaryFileOrDie'


there would be something wrong with my environment on OpenCV(4.5.3) ,  but I have no any ideas about that.

**Comment by cansik** [comment]
Please check if the libraries are downloaded correctly on your system. They should be in `Documents/Processing/Libraries/deepvision/library/networks`. `candy.t7` should be about `15.6 MB`.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/5220162/155894214-67ddf611-c525-4170-a342-d584c6a689c6.png">

**Comment by lymanzhang** [comment]
thanks, the reason is really because of the incompleted downloads.
