### ISSUE TITLE
realsense example breaks with realsense update 2.3.0

### ISSUE THREAD

**Issue by brad-miller** [cansik/deep-vision-processing#5]
Hi cansik
thanks for your brilliant work!
update 2.4.0 seems to break deepvision (0.4.0) realsense examples 
throws a RealSenseException: std::bad_cast
kind regards

**Comment by cansik** [comment]
Hi Brad, thank you for reporting, it could be a problem with the javacpp library that is included and in a different version (1.5.3 in deep-vision and 1.5.4 in realsense). I will have to verify it quickly.

**Comment by cansik** [comment]
The problem was that java-cv contains librealsense java bindings that are outdated atm. I had to remove them so that the newer ones from the realsense-library could be used. Please try it out in version [0.5.0](https://github.com/cansik/deep-vision-processing/releases/tag/v0.5.0-alpha).

**Comment by brad-miller** [comment]
Issue is now resolved....thanks you for your prompt response.....

**Comment by cansik** [comment]
Your welcome! Thanks for reporting the issue.
Would be interesting to see what you are doing with the library :)

**Comment by brad-miller** [comment]
Thanks Florian

Experimenting with various approach to creating robust low cost art installation tracking system

Happy to talk more

Kind regards

Sent from my iPhone

On 7 Feb 2021, at 10:48 am, Florian Bruggisser <notifications@github.com> wrote:

﻿

Closed #5<https://github.com/cansik/deep-vision-processing/issues/5>.
