### ISSUE TITLE
CUDA Enabled error

### ISSUE THREAD

**Issue by 0000marcosg** [cansik/deep-vision-processing#9]
Hi, 

I trying to run some of the examples on CUDA and I am getting the following error:

`[ WARN:0] global modules\dnn\src\dnn.cpp (1442) cv::dnn::dnn4_v20201117::Net::Impl::setUpNet DNN module was not built with CUDA backend; switching to CPU`

I read something about incompatibilities with OpenCV for Processing, and for some google results I guessing that maybe it can be related to that.  

On the other hand, congratulations on this project!

**Comment by cansik** [comment]
Hi, please check the following things:

1. Are you running it on a Linux or Windows (x64 or x86)?
2. Have you downloaded the [CUDA bundled version](https://github.com/cansik/deep-vision-processing/releases/tag/v0.6.2-alpha) of the library (either specifically for your system or the 5 GB zip file from google drive)?
3. Which network (or example) are you trying to run?

CUDA is huge and so I do not share it by default through the contribution manager.

**Comment by 0000marcosg** [comment]
Sorry. I was totally confused about which version to download. It was solved by downloading the 1.5GB version for windows.

**Comment by cansik** [comment]
Thanks, I've added a direct link to the readme!

**Comment by TiagoTiago** [comment]
Why is there no CUDA zip for 0.9.0?

**Comment by cansik** [comment]
Because Github only supports release-assets below 2GB of size. I switched to CI builds but had to disable the CUDA one because of their size. You can build them on your own if you need to.
